### ISSUE TITLE
nycc_pal deprecation

### ISSUE THREAD

**Issue by nmontalbanocouncil** [NewYorkCityCouncil/councildown#24]
Decide whether or not to deprecate nycc_pal for pal_nycc. If so, will have to deal with other functions that depend on nycc_pal. For example: https://github.com/NewYorkCityCouncil/councildown/blob/50a381b457427f05adad7a6417d68bdd361ee188/R/colors.R#L187

**Comment by romartinez-nycc** [comment]
#### Initial look into the dependencies of nycc_pal and it looks like we can sort everything out within just the color.R file.

inherits/depends:
- `scale_fill_nycc()` on `nycc_pal()`
- `scale_color_nycc()` on `scale_fill_nycc()`
- `scale_color_discrete()` on `scale_color_nycc()`
- `scale_color_continuous()` on `scale_color_nycc()`
- `scale_fill_discrete()` on `scale_fill_nycc()`
- `scale_fill_continuous()` on `scale_fill_nycc()`


#### it all starts with `scale_fill_nycc()`:

https://github.com/NewYorkCityCouncil/councildown/blob/da68590beddc64ee91aa348f69292563ddde1148/R/colors.R#L170-L181

Maybe we can test run to see what breaks by swapping out `nycc_pal` for `pal_nycc` and taking out the `scale_fill_gradientn(colours = pal(256)` line?
