### ISSUE TITLE
Sp retiring

### ISSUE THREAD

**Issue by romartinez-nycc** [NewYorkCityCouncil/councildown#29]
>  Loading councildown .......................
> The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
> which was just loaded, will retire in October 2023.
> 
> Please refer to R-spatial evolution reports for details, especially
> https://r-spatial.org/r/2023/05/15/evolution4.html.
> 
> It may be desirable to make the sf package available;
> package maintainers should consider adding sf to Suggests:.
> The sp package is now running under evolution status 2 (status 2 uses the sf package in place of rgdal)

**Comment by nmontalbanocouncil** [comment]
We get this error because `mapshot` depends on `mapview`, which loads `sp`. Not sure of a fix unless we stop using mapshot. Hopefully `mapview` only loads `sp` because it supports `sp` spatial classes. I wonder what will happen next month when `sp` is officially retired...

**Comment by romartinez-nycc** [comment]
Lol just saw your comment after looking into for your pull request
