### ISSUE TITLE
Two zoom controls 

### ISSUE THREAD

**Issue by nmontalbanocouncil** [NewYorkCityCouncil/councildown#43]
This is making it so my maps have two zoom controls, one on the top left and one on the top right. Are others getting the same?

https://github.com/NewYorkCityCouncil/councildown/blob/b836c5a198d5303412c273518632d9a8f881bf60/R/addCouncilStyle.R#L30 

Maybe we have to add `map$x$options$zoomControl = F`  after here?
https://github.com/NewYorkCityCouncil/councildown/blob/b836c5a198d5303412c273518632d9a8f881bf60/R/addCouncilStyle.R#L24

**Comment by romartinez-nycc** [comment]
Hmm, interesting I thought I got it to just have the zoom control on the top right, so it won't interfere with the legend that tends to be placed on the top left.

**Comment by nmontalbanocouncil** [comment]
Looks like somehow the `zoomControl = FALSE` that you had put in earlier got deleted in later merges. 

https://github.com/NewYorkCityCouncil/councildown/commit/d50e2fdc437887403d0e7d0a0f84226ae5b48a56#diff-b7b5426ac969d81d2bb60d02ee3a755331509327425b1381dfcbc367d7b22c64R26

I think just adding `map$x$options$zoomControl = F` will fix it so I'll make a PR for that.
